### ISSUE TITLE
Include greeksubs.net

### ISSUE THREAD

**Issue by pRieStaKos** [Twilight0/service.subtitles.subtitles.gr#10]
As many greek sub websites are blocked by ISP or down, can you update the subs providers of the plugin to include `greeksubs.net` or other available too ?

Thank you in advance.

**Comment by Twilight0** [comment]
This website is supported on another addon be fellow developer @bugatsinho: https://github.com/bugatsinho/bugatsinho.github.io/tree/master/service.subtitles.greeksubs
