### ISSUE TITLE
Subtitles not showing

### ISSUE THREAD

**Issue by dimitris90s** [Twilight0/service.subtitles.subtitles.gr#3]
Hello my friend, i want to report an issue with kodi.

After the close down of many Greek subtitle sites the addon can't find many subtitles for movies or shows.
I don't know if there is something you could do about it because in Greece we can't enter these sites without proxy.

I appreciate your work to the community all these years, peace )

**Comment by Twilight0** [comment]
Change your DNS servers into something like Cloudflare's (1.1.1.1 & 1.0.0.1), then have patience until subtitles.gr is brought back to life:

https://downforeveryoneorjustme.com/subtitles.gr

**Comment by dimitris90s** [comment]
Problem solved with changing dns! I runned some tests and i put Google's dns.
I find out that subs4free changed their site to:
https://www.subs4free.info/
Is this site on the addon?
Thanks a lot for your help!

**Comment by Twilight0** [comment]
No, subs4free is not included into subtitles.gr addon but rather in a fellow developer's one: https://github.com/bugatsinho/bugatsinho.github.io/tree/master/service.subtitles.greeksubs

Closing this issue.
