### ISSUE TITLE
subsxyz

### ISSUE THREAD

**Issue by Rady7** [Twilight0/service.subtitles.subtitles.gr#4]
Καλημερα και απο δω https://prntscr.com/lxh8eh

**Comment by Twilight0** [comment]
Καλό θα ήτανε να έχουμε ολόκληρο το log διαθέσιμο, γιατί το παραπάνω δεν μου λέει απολύτως τίποτα. Έτσι όπως είναι γραμμένο το πρόσθετο, το συγκεκριμένο είναι συνηθισμένο, παρ' όλ' αυτά όμως είναι και μια καλή ευκαιρία να αλλαχτεί αυτή η συμπεριφορά και να γράφει στο log ακριβώς τι συμβαίνει.

**Comment by Twilight0** [comment]
Κλείνω το issue γιατί δεν μπορώ να καταλάβω από που προέρχεται το σφάλμα.
1) Πρέπει να έχω ολόκληρο το log ή έστω το εξής: "Προσπάθησα να αναπαράγω την τάδε ταινία και δεν βρίσκει τίποτα" Ή "Δεν κατεβάζει τον υπότιτλο στο τάδε επεισόδιο της δείνας σειράς"
2) Βάση δοκιμών που έκανα, το subz.xyz μπορεί να κατεβάσει υπότιτλους, αλλά δεν μπορεί να τους ανοίξει όταν έχει πολλαπλά αρχεία. Η λύση βρίσκεται στο νεότερο Kodi Leia με τα νέα vfs τύπου πρόσθετα που ανοίγουν rar πακέτα.
