### ISSUE TITLE
AliveGr issue

### ISSUE THREAD

**Issue by djpikos** [Twilight0/service.subtitles.subtitles.gr#5]
Καλησπέρα και χρόνια πολλά. 
Τρέχω το alivegr από το kodi και δυστυχώς περίπου τις τελευταίες 3 εβδομάδες μου βγάζει error και δεν δουλεύει. Υπάρχει κάποιο workaround που θα μπορούσα να κάνω για να δουλέψει?

**Comment by Twilight0** [comment]
Θα γράψεις για το πρόβλημά σου εδώ, με το log, αλλιώς δεν μπορώ να καταλάβω τι πρόβλημα αντιμετωπίζεις: https://bitbucket.org/thgiliwt/plugin.video.alivegr/issues?status=new&status=open
