### ISSUE TITLE
subz.xyz

### ISSUE THREAD

**Issue by gusmin1975** [Twilight0/service.subtitles.subtitles.gr#6]
[kodilog.txt](https://github.com/Twilight0/service.subtitles.subtitles.gr/files/2802367/kodilog.txt)

Όποιον υπότιτλο και να επιλέξω από subz.xyz μου βγάζει error. Αν επιλέξω από other τον κατεβάζει κανονικά.

**Comment by Twilight0** [comment]
Σε Leia θέλει εγκατεστημένο το vfs.libarchive.
