### ISSUE TITLE
Λάθος file.extension

### ISSUE THREAD

**Issue by fotvet** [Twilight0/service.subtitles.subtitles.gr#7]
Όταν γίνει download ο υποτιτλός στο φάκελλο είναι της μορφής moviename.el.Broke ή moviename.el.h264..... μάλλον έχει θέμα με το split και δεν παίρνει σώστα το extension από το αρχικό αρχείο sub.

**Comment by Twilight0** [comment]
Θα ήθελα να δω ακριβώς όνομα αρχείου ώστε να μπορέσω να το κάνω αποσφαλμάτωση.

**Comment by jded76** [comment]
Για να σε βοηθήσω όσο μπορώ, μιας και έριξα μια ματιά στο κώδικα, το λάθος πρέπει να βρίσκεται στα αρχεία subtitlesgr.py, subzxyz.py και xsubstv.py. 

Ειδικότερα στη γραμμή που κάνεις το παρακάτω:
[result = control.join(os_split(subtitle)[0], 'subtitles.' + os_split(subtitle)[1].split('.')[1])](https://github.com/Twilight0/service.subtitles.subtitles.gr/blob/4f644002550a761fc3ad6282c57d82bd5c8e3524/resources/lib/subzxyz.py#L267)

Αν το filename περιέχει πολλές τελείες (π.χ. game.of.thrones.s08e05.1080p.amzn.web-dl.ddp5.1.h.264-got.srt) παίρνεις λάθος extension (σώνεται ως .of αντί για .srt).

Αντί για το split('.')[1] πρέπει να πάρεις το τελευταίο element στο split (αντί για το 1).

Δοκίμασε το με [αυτόν τον υπότιτλο](http://files.subz.xyz/repository/Series/G/Game%20of%20Thrones%20%282011%29/Season%2008/Episode%2005/game.of.thrones.s08e05.1080p.amzn.web-dl.ddp5.1.h.264-got.rar)

**Comment by jded76** [comment]
Έχω κάνει τις αλλαγές και σου έχω κάνει pull request. 
Δε το έχω δοκιμάσει όμως, μιας και δεν έχω ξανασχοληθεί με kodi addons. 
Αν θες τσεκαρε το και πες μου.

**Comment by jded76** [comment]
Τελικά έκανα copy τα 3 αρχεία που άλλαξα στο δικό μου kodi και είδα ότι έσωσε τον υπότιτλο με το σωστό extension.

**Comment by Twilight0** [comment]
Ok θα το ενσωματώσω.
