### ISSUE TITLE
subztv.online

### ISSUE THREAD

**Issue by pRieStaKos** [Twilight0/service.subtitles.subtitles.gr#9]
Hello, 

Thanks for this addon. 

As many ISP are blocking `subtitles.gr`, can you add `subztv.online` in the addon service ?

Thank you in advance.

**Comment by Twilight0** [comment]
I am using an alternate domain name for subtitles.gr at the moment, so this shouldn't be an issue, the point is that subtitles.gr has frequent downtimes. subztv.online is already supported by [greeksubs](https://github.com/bugatsinho/bugatsinho.github.io/tree/master/service.subtitles.greeksubs)

**Comment by pRieStaKos** [comment]
Thank you for the clarification. Keep up
